export default [
  {
    chainId: 'medasdigital-1',
    name: 'MedasDigital',
    slot: "MedasDigital",
    desc: '',
    apiURL: 'https://lcd.medas-digital.io:1317',
    rpcURL: 'https://rpc.medas-digital.io:26656',
    coinLookup: {
      viewDenom: 'MEDAS',
      chainDenom: 'umedas',
      addressPrefix: 'medas',
      icon: `https://raw.githubusercontent.com/cosmos/chain-registry/master/medasdigital/images/medas.svg`,
      banner: "https://pbs.twimg.com/profile_banners/602625556/1649007099/1500x500",
    },
    explorerUrl: 'https://explorer.medas-digital.io:3000/medasdigital/tx/',
    coingeckoId: 'medasdigital',
    feeMultiplier: 1.9,
    gasPrice: 0.0025,
    maxTxSenderHome: 5,
    maxTxRecipientHome: 5,
    maxTxSender: 50,
    maxTxRecipient: 50,
    color: '#33ffc9',
    colorChart: ["#b3ffeb", "#33ffc9", "#00b383", "#004d38"], 
    modules: {
      feeGrant: true,
      authz: true,
      wasm: false,
      group: true,
    }
  },
  {
    chainId: 'medasdigital-1',
    name: 'MedasDigital Network',
    desc: ' ',
    slot: "medasdigital",
    apiURL: 'https://lcd.medas-digtal.io:1317',
    rpcURL: 'https://rpc.medas-digital.io:26656',
    coinLookup: {
      viewDenom: 'MEDAS',
      chainDenom: 'umedas',
      addressPrefix: 'medas',
      icon: `https://raw.githubusercontent.com/cosmos/chain-registry/master/medasdigital/images/medas.svg`,
      banner: "https://pbs.twimg.com/profile_banners/602625556/1649007099/1500x500",
    },
    explorerUrl: 'https://explorer.medas-digital.io:3100/transactions/',
    coingeckoId: 'medasdigital',
    feeMultiplier: 1.9,
    gasPrice: 0.0025,
    maxTxSenderHome: 5,
    maxTxRecipientHome: 5,
    maxTxSender: 50,
    maxTxRecipient: 50,
    color: '#33ffc9',
    colorChart: ["#b3ffeb", "#33ffc9", "#00b383", "#004d38"],
    modules: {
      feeGrant: true,
      authz: true,
      wasm: false,
      group: true,
    }
  },
  {
    chainId: 'medasdigital-1',
    name: 'MedasDigital',
    desc: ' ',
    slot: "medasdigital",
    apiURL: 'https://lcd.medas-digital.io:1317',
    rpcURL: 'https://rpc.medas-digital.io:26656',
    coinLookup: {
      viewDenom: 'MEDAS',
      chainDenom: 'umedas',
      addressPrefix: 'medas',
      icon: `https://raw.githubusercontent.com/cosmos/chain-registry/master/medasdigital/images/medas.svg`,
      banner: "https://pbs.twimg.com/profile_banners/602625556/1649007099/1500x500",
    },
    explorerUrl: 'https://explorer.medas-digital.io:3100/transactions/',
    coingeckoId: 'medasdigital',
    feeMultiplier: 1.9,
    gasPrice: 0.0025,
    maxTxSenderHome: 5,
    maxTxRecipientHome: 5,
    maxTxSender: 50,
    maxTxRecipient: 50,
    color: '#33ffc9',
    colorChart: ["#b3ffeb", "#33ffc9", "#00b383", "#004d38"],
    modules: {
      feeGrant: true,
      authz: true,
      wasm: false,
      group: true,
    }
  },  
]
